name: Build Program

on:
  push:
  workflow_dispatch:
    inputs: 
      BuildBranch:
        description: 'The branch you want to build.' 
        required: true
        default: 'master'
      BuildConfiguration:
        description: 'The configuration for dotnet build.'
        required: true
        default: 'Release'
        type: choice
        options: 
          - Release
          - Debug
    
env:
  DEFAULT_CONFIGUTATION: "Release"
  DEFAULT_BRANCH: "master"
  Version: 0.2.8

jobs:
  build:
    runs-on: windows-latest
    env:
      Configuration: ${{${{ github.event.inputs.BuildConfiguration || env.DEFAULT_CONFIGUTATION }}}}
      Branch: ${{ github.event.inputs.BuildBranch || env.DEFAULT_BRANCH }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ env.Branch }}
        submodules: recursive
    - name: Setup .NET5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish .\OngekiFumenEditor\OngekiFumenEditor.csproj --no-restore -c ${{build.env.Configuration}} -o ./bin/githubActions/
    # - name: Enum files
    #  run: Get-ChildItem -Recurse
    - uses: actions/upload-artifact@v3
      with:
        name: OngekiFumenEditor_${{build.env.Branch}}_${{build.env.Configuration}}_${{env.Version}}
        path: D:\a\OngekiFumenEditor\OngekiFumenEditor\bin\githubActions
    
