name: Build Program

on:
  push:
  workflow_dispatch:
    inputs: 
      BuildBranch:
        description: 'The branch you want to build.' 
        required: true
        default: 'master'
      BuildConfiguration:
        description: 'The configuration for dotnet build.'
        required: true
        default: 'Release'
        type: choice
        options: 
          - Release
          - Debug
    
env:
  Configuration: ${{ github.event.inputs.BuildConfiguration || 'Release' }} 
  Branch: ${{ github.event.inputs.BuildBranch || github.ref_name }}

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ env.Branch }}
        submodules: recursive
    - name: Setup .NET5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: get-version-action
      uses: bbonkr/get-version-action@v1.0.4
      with:
        project: D:\a\OngekiFumenEditor\OngekiFumenEditor\version.json
    - name: logging
      run: echo "Version=${{ steps.get_version.outputs.version }}"
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish .\OngekiFumenEditor\OngekiFumenEditor.csproj --no-restore -c ${{env.Configuration}} -o ./bin/githubActions/
    # - name: Enum files
    #  run: Get-ChildItem -Recurse
    - uses: actions/upload-artifact@v3
      with:
        name: OngekiFumenEditor_${{steps.get_version.outputs.version}}_${{env.Configuration}}_${{env.Version}}
        path: D:\a\OngekiFumenEditor\OngekiFumenEditor\bin\githubActions
    
